Yleisradio/yle_tf

.rubocop.yml
bin/tf
lib/yle_tf/plugin/loader.rb
yle_tf.gemspec

Check that Bundler is really set up before loading plugins with it. Requiring 'bundler/setup' won't do much if the Gemfile is not found, leaving `Bundler.require` undefined.
Also exclude the Gemfile (and other non-ruby code) from the gem.

Fix Bundler plugin loading errors

---

lib/yle_tf/cli.rb
lib/yle_tf/logger.rb
lib/yle_tf/logger/colorize.rb
lib/yle_tf_plugins/commands/__default/command.rb
lib/yle_tf_plugins/commands/help/command.rb

Output all kind of error messages in the `Logger` with colors by default.
Can be turned off with `--no-color`, which is also passed to the Terraform command.

Colors for error and warning messages

---

.rubocop.yml
lib/yle_tf/action/terraform_init.rb
lib/yle_tf/action/verify_terraform_version.rb
lib/yle_tf/logger.rb
lib/yle_tf/system.rb
lib/yle_tf/system/io_handlers.rb
lib/yle_tf/system/output_logger.rb
lib/yle_tf/system/tf_hook_output_logger.rb
lib/yle_tf/tf_hook.rb
lib/yle_tf_plugins/commands/__default/command.rb
lib/yle_tf_plugins/commands/help/command.rb
lib/yle_tf_plugins/commands/version/command.rb
spec/yle_tf/tf_hook_spec.rb

Especially when initializing Terraform, redirect STDOUT as "debug" level to hide all the verbose output by default. The actual executed Terraform command will still use `system` as before.
Also allows YleTf hooks to emit log messages with specific levels by prefixing a line with `<LEVEL>: `, for example `DEBUG: foo`.

Support for IO handlers for `System.cmd` commands, pipe most command and hook output to Logger

---

lib/yle_tf/action/terraform_init.rb

Set the [`TF_IN_AUTOMATION`](https://www.terraform.io/guides/running-terraform-in-automation.html) environment variable for Terraform initialization commands to reduce some help output (which will be shown only in debug output level anyway).

Reduce some output of the Terraform initialization

---

lib/yle_tf/action/terraform_init.rb

The commands will output with DEBUG level which is hidden by default.
So the `tf` just seems to get stuck. Better to error out if interaction is needed.
Fixes #8

Deny interaction when initializing Terraform

---

lib/yle_tf/action.rb
lib/yle_tf/action/write_terraformrc_defaults.rb
lib/yle_tf_plugins/commands/version/plugin.rb

Add configuration to `~/.terraformrc` if the keys are not already set:
* Disable Terraform upgrade and security bulletin checks
* Configure global Terraform plugin cache
Docs: https://www.terraform.io/docs/commands/cli-config.html

Write default Terraform CLI configuration

---

lib/yle_tf/system/io_handlers.rb
lib/yle_tf/system/output_logger.rb

Catch IOErrors when reading inputs on Threads to avoid output when the input IO is being closed due to e.g. Ctrl+C.
Still log the error with stack trace with debug level.

Handle IOErrors in IO Handlers

---

README.md
lib/yle_tf_plugins/backends/swift/command.rb
lib/yle_tf_plugins/backends/swift/plugin.rb

Add support for using OpenStack Swift as a backend. [Terraform docs](https://www.terraform.io/docs/backends/types/swift.html).
Required configuration key: `container`. Optional: `region` and `archive_container`.

Add support for Swift backend

---

lib/yle_tf/vars_file.rb

While string based variables are most common, aws_lambda_function wants to get its variables as a map. This solution would make it possible.

Support map type (in addition to string) in terraform.tfvars

---

lib/yle_tf/config/defaults.rb

Make it easier to build e.g. unique backend S3 object names based on the full path to the module.

Add `module_dir` to the tf.yml evaluation context

---

lib/yle_tf/action/load_config.rb
lib/yle_tf/config.rb
test/unit/yle_tf/action/load_config_spec.rb
test/unit/yle_tf/config_spec.rb

With config like:
```yaml
foo:
bar: something
```
`fetch('foo', 'bar', 'baz')` raised an exception instead of normal "key not found" handling.
Also make the `Config` class easier to test by extracting loading out of the constructor, and add some unit tests.

Fix `Config.fetch` when a key is not a Hash and refactor config loading

---

lib/yle_tf.rb
lib/yle_tf/action/terraform_init.rb
lib/yle_tf/action/verify_terraform_version.rb
lib/yle_tf/backend_config.rb
lib/yle_tf/version_requirement.rb
lib/yle_tf_plugins/backends/file/config.rb
test/unit/yle_tf/action/verify_terraform_version_spec.rb
test/unit/yle_tf/version_requirement_spec.rb

The support has been actually broken for year now, since PR #9. Nobody has complained, so clean up the code base a bit.
Anyway, add a check and clear error message for old Terraform versions. And unit tests. Yay!

 Drop (broken) support for Terraform 0.8 and older

---

README.md
lib/yle_tf/action.rb
lib/yle_tf/action/verify_yle_tf_version.rb
lib/yle_tf/config/defaults.rb
test/unit/yle_tf/action/verify_yle_tf_version_spec.rb
test/unit/yle_tf/config/loader_spec.rb

In some configuration migrations (as would have been nice to have for v1.1), possible hook interface changes, etc., it can be useful to specify the minimum YleTf version in `tf.yaml`:
```yaml
yle_tf:
version_requirement: ">= 1.2"
```

Allow configuring YleTf version requirement in tf.yaml

---

lib/yle_tf/action/tf_hooks.rb
test/unit/yle_tf/action/tf_hooks_spec.rb

Sometimes it is useful to know the original module root path, so that hooks can access files in it if needed. For example when persisting downloaded files.
Also add unit tests for the `Action::TfHooks` class.

Pass original module directory to hooks as `TF_MODULE_DIR` env var

---

.rubocop.yml
.travis.yml
lib/yle_tf/cli.rb
yle_tf.gemspec

Ruby 2.3 reached EOL on 2019-03-31:
https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/
- Require Ruby 2.4+ for the gem
- Update Ruby version matrix in Travis build
- Upgrade and fix Rubocop Rules for 2.4
- Upgrade Rake to 13.0

Drop support for Ruby v2.3

---

.travis.yml
README.md

Especially, add Terraform 0.12 to the test matrix.

Update Terraform versions in acceptance tests

---

CHANGELOG.md
lib/yle_tf/action/write_terraformrc_defaults.rb
test/acceptance/fixtures/terraformrc

The `~` might not be evaluated in all environments.

Use `$HOME` instead of `~` in default .terraformrc

---

.rubocop.yml
.travis.yml
lib/yle_tf/action/terraform_init.rb
lib/yle_tf/config.rb
lib/yle_tf/config/loader.rb
lib/yle_tf/system.rb
lib/yle_tf/system/io_handlers.rb
test/unit/yle_tf/action/load_config_spec.rb
test/unit/yle_tf/action/verify_terraform_version_spec.rb
test/unit/yle_tf/action/verify_yle_tf_version_spec.rb
test/unit/yle_tf/config/migration_spec.rb
test/unit/yle_tf/config_spec.rb
yle_tf.gemspec

EDIT: I rearranged and amended to the original PR to fix the tests etc. - @tmatilai 
* https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/
* Add missing dependencies for Ruby 2.7
- Ruby 2.7.0 no longer includes `thwait` and `e2mmap` as system libraries
- `e2mmap` is a (missing) dependency of `thwait`, so we must declare it until the next thwait release.no longer includes thwait and e2mmap as system libraries
* Fix keyword argument warnings for Ruby 2.7
- Automatic conversion of keyword arguments and positional arguments is deprecated, and conversion will be removed in Ruby 3.
* Add Ruby 2.7.0 to the test matrix
* Update tested Terraform versions
* Update Rubocop configuration for recent versions

Fix compatibility with Ruby 2.7.0

---

lib/yle_tf/action/terraform_init.rb
test/unit/yle_tf/action/terraform_init_spec.rb

Terraform stores state in `errored.tfstate` if it fails to persist a state to a backend. As YleTf runs in a temporary directory, it would be lost and recovery gets complicated.
So make a symlink to the module dir to store an errored tfstate.
Also add unit tests for the `TerraformInit` class.

Symlink `errored.tfstate` from run dir to module dir

---

lib/yle_tf_plugins/commands/help/command.rb

The output format changes between Terraform versions. The list is also really long. So guide the user to call `terraform -help` to get it.
Fixes #37

Don't try to list all Terraform commands

---

lib/yle_tf/action/terraform_init.rb
test/unit/yle_tf/action/terraform_init_spec.rb

Terraform 0.14 introduced dependency lock file:
https://www.terraform.io/docs/configuration/dependency-lock.html
Terraform does not follow the symlink for `.terraform.lock.hcl`, but replaces it with new file. So copy the generated/updated file back to the module dir right after calling `terraform init`.
This seems safe and consistent also in case of (Terraform) failures. It also feels best to use only one lock file for all environments.
Downside of the YleTf's init behaviour is that the Terraform output is "hidden" as debug output, and that the `terraform init` command is hardcoded. Add two features to ease up a bit:
- Support passing arguments to the automatic init call with  `TF_INIT_ARGS` environment variable.
- Skip the internal init call if `tf <env> init [args]` is called. This …

Store Terraform 0.14+ version lock file

---

lib/yle_tf/action/write_terraformrc_defaults.rb

Do not force the settings if the config file already exist.
Still warn about missing `plugin_cache_dir` setting as it might slow down YleTf execution by loading the plugins every time to the temporary directory.
Also fix the plugin cache directory existence check that was accidentally broken in #29.
Fixes: #34

Write terraformrc only if it doesn't exist

---

README.md
lib/yle_tf/action/terraform_init.rb
lib/yle_tf/backend.rb
lib/yle_tf/config/defaults.rb
lib/yle_tf_plugins/backends/file/backend.rb
test/unit/yle_tf/action/terraform_init_spec.rb
test/unit/yle_tf/config/loader_spec.rb

Add support for automatically encrypting and decrypting the state file when using the (default) `file` backend. The feature is still experimental as functionality might change after gaining experience and feedback.
If encryption is enabled, instead of symlinking, the state file is decrypted from the `path` to the temporary working directory just before initializing Terraform, and decrypted back after running the actual command.
If the encryption fails, the uncrypted state file is copied to "`path`.plaintext" for the user to encrypt manually.
By default the encryption is done using [sops](https://github.com/mozilla/sops#readme), but the whole file is encrypted instead of just leaf values, as the whole content is anyway encrypted on every run.
Sops can be configured further (e.g. the keys) …

Support encrypting file backend states

---

lib/yle_tf/logger.rb

With ruby's logger best alternative would be to map TRACE into DEBUG.
References:
- https://ruby-doc.org/stdlib-3.0.0/libdoc/logger/rdoc/Logger.html
- https://www.terraform.io/docs/internals/debugging.html
Work-around:
Define TF_DEBUG=1 TF_LOG=TRACE.
This way yle_tf will respond to TF_DEBUG and TF_LOG gets passed to terraform as it is.

[logger] terraform supports TF_LOG=TRACE

---

CHANGELOG.md
lib/yle_tf/system/tf_hook_output_logger.rb

To avoid this type of situations:
```
#<Thread:0x000055c4570a5908 /usr/yle-aws-tools/.gems/ruby/2.7.0/gems/yle_tf-1.4.0/lib/yle_tf/system/output_logger.rb:17 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
4: from /usr/yle-aws-tools/.gems/ruby/2.7.0/gems/yle_tf-1.4.0/lib/yle_tf/system/output_logger.rb:19:in `block in call'
3: from /usr/yle-aws-tools/.gems/ruby/2.7.0/gems/yle_tf-1.4.0/lib/yle_tf/system/output_logger.rb:19:in `each'
2: from /usr/yle-aws-tools/.gems/ruby/2.7.0/gems/yle_tf-1.4.0/lib/yle_tf/system/output_logger.rb:19:in `block (2 levels) in call'
1: from /usr/yle-aws-tools/.gems/ruby/2.7.0/gems/yle_tf-1.4.0/lib/yle_tf/system/tf_hook_output_logger.rb:16:in `log'
/usr/yle-aws-tools/.gems/ruby/2.7.0/gems/yle_tf-1.4.0/lib/yle_tf/syst …
```

[tf_hook_output_logger] Encode string so that String.sub() works

---

CHANGELOG.md
lib/yle_tf/system/tf_hook_output_logger.rb

When we get output from terraform hook, the problem is that content is labeled as US-ASCII and String.encode won't solve that one. However, String.force_encoding will let ruby know that content is in UTF-8, even if it has originally assumed that it is something ele.
Rescue tries to guarantee that our deployment won't suffer complete failure in post-hook phase.

[tf_hook_output_logger] Use force_encoding instead of encoding.
